#!/bin/bash
# Script to display git log for creating timesheet by Puneet Behl @ IntelliGrape Software (P) Ltd. Feb 25, 2013 09:00:00 
  
   TODAY=`date +%Y%m%d`
   EXPECTED_ARGS=1
   E_BADARGS=65
   DATE_REGEX="[1-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]"
   DAY_REGEX="[0-3][0-9]"
   if [ $# -lt $EXPECTED_ARGS ]
   then
       git log --pretty="short" --format=%Cblue%h%' 'Cgreen%an[%ad]%' 'Creset%s%n --date=short
   fi

   if [[ $# -eq $EXPECTED_ARGS && $1 =~ $DATE_REGEX ]]
   then
       git log --pretty="short" --format=%Cblue%h%' 'Cgreen%an[%ad]%' 'Creset%s%n --date=short --after={$1}
   fi

   if [[ $# -gt $EXPECTED_ARGS && $# -eq 2 && $1 =~ $DATE_REGEX && $2 =~ $DATE_REGEX ]]
   then
       git log --pretty="short" --format=%Cblue%h%' 'Cgreen%an[%ad]%' 'Creset%s%n --date=short --before={$2} --after=${1}
   fi

   if [[ $# -eq $EXPECTED_ARGS && $1 =~ $DAY_REGEX ]]
   then
       git log --pretty="short" --format=%Cblue%h%' 'Cgreen%an[%ad]%' 'Creset%s%n --date=short --after={$1-%m-%Y}
   fi

   if [[ $# -gt $EXPECTED_ARGS && $# -eq 2 && $1 =~ $DAY_REGEX && $2 =~ $DAY_REGEX ]]
   then
       git log --pretty="short" --format=%Cblue%h%' 'Cgreen%an[%ad]%' 'Creset%s%n --date=short --before={$2-%m-%Y} --after={$1-%m-%Y}
   fi
